# Generated by Django 4.2.7 on 2023-11-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregister',
            name='code',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
