# Generated by Django 5.0 on 2023-12-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_carregister_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carregister',
            options={},
        ),
    ]
