# Generated by Django 5.0 on 2023-12-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_options_alter_carregister_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='carregister',
            options={'get_latest_by': ('enter_date', 'leave_date'), 'ordering': ('enter_date', 'leave_date'), 'verbose_name': 'CarRegister', 'verbose_name_plural': 'CarRegisters'},
        ),
    ]
