# Generated by Django 4.2.7 on 2023-11-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_url',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default='a', max_length=128),
            preserve_default=False,
        ),
    ]
