# Generated by Django 4.2.7 on 2023-11-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0002_alter_carregister_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(null=True)),
                ('payment_url', models.URLField(max_length=512)),
                ('car_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carregister')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('paid_date',),
                'get_latest_by': ('paid_date',),
            },
        ),
    ]
